# Generated by Django 4.2.30 on 2026-04-17 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_file', models.FileField(upload_to='tmp/')),
                ('content_type', models.CharField(blank=True, max_length=120)),
                ('target_job_title', models.CharField(blank=True, max_length=255)),
                ('job_description', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('overall_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hire_probability', models.CharField(blank=True, max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('keywords_missing', models.JSONField(blank=True, default=list)),
                ('keywords_found', models.JSONField(blank=True, default=list)),
                ('ats_risk', models.CharField(blank=True, max_length=20)),
                ('ats_risk_explanation', models.CharField(blank=True, max_length=255)),
                ('raw_analysis', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('share_enabled', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
